---
name: Scheduled build for latest docs
"on":
  schedule:
    # Run at 05:41 on Monday
    - cron: '41 5 * * 1'

permissions:
  contents: read

jobs:
  build-package-docs:
    if: github.repository == 'ansible/ansible-documentation'
    name: 📝 Build
    uses: ./.github/workflows/reusable-build-docs.yaml
    with:
      repository-branch: 'stable-2.20'
      ansible-package-version: '13'
    secrets:
      DOCS_BOT_TOKEN: ${{ secrets.DOCS_BOT_TOKEN }}

  deploy-package-docs:
    name: 🚀 Deploy
    needs: build-package-docs
    uses: ./.github/workflows/reusable-deploy-docs.yaml
    with:
      ansible-package-version: '13'
      deployment-environment: 'production'
      repository-branch: 'stable-2.20'
    secrets:
      DEPLOY_DOC_BUILD: ${{ secrets.DEPLOY_DOC_BUILD }}
