name: ansible-release-porting-guide
on:
  workflow_dispatch:
    inputs:
      ansible-version:
        description: >-
          Release Version. Example : 11.1.0
        required: true
      ansible-major-version:
        description: 'Example 11'
        required: true

env:
  CI_COMMIT_MESSAGE: 'Add Ansible community "${{ inputs.ansible-version }}" porting guide'
  CI_PR_BODY: |

      ##### SUMMARY

      ##### ISSUE TYPE

      - Docs Pull Request

      ##### COMPONENT NAME

      docs/docsite/rst/porting_guides/'porting_guide_"${{ inputs.ansible-major-version }}".rst'

jobs:
  build:
    name: 'Build PortingGuide (${{ inputs.ansible-version }})'
    runs-on: ubuntu-latest

    steps:

# checkout the /ansible/ansible-documentation & ansible-build-data
      - name: Check out ansible-documentation
        uses: actions/checkout@v3
        with:
          path: ansible-documentation
          ref: devel

      - name: Checking out to a new branch & setting the user details
        working-directory: ansible-documentation
        run: |
          git checkout -b "publish-${{ inputs.ansible-version }}"
          git config --global user.name "Github Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

# Get the Porting guide from the tarball

      - name: Commit ansible-documentation
        run: |
          wget https://files.pythonhosted.org/packages/source/a/ansible/'ansible-${{ inputs.ansible-version }}'.tar.gz
          tar -xzf 'ansible-${{ inputs.ansible-version }}'.tar.gz
          cp 'ansible-${{ inputs.ansible-version }}'/'porting_guide_${{ inputs.ansible-major-version }}.rst' ./ansible-documentation/docs/docsite/rst/porting_guides/

# the actual steps for commit

      - name: Push the changes to ansible-documentation github repo
        working-directory: ansible-documentation
        run: |
         git add ./docs/docsite/rst/porting_guides/"porting_guide_${{ inputs.ansible-major-version }}.rst"
         git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
         git push origin "publish-${{ inputs.ansible-version }}"
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the PR body
        working-directory: ansible-documentation
        run: |
          python3 -c "import os; file = open('pr_body.txt', 'w'); file.write(os.environ['CI_PR_BODY']); file.close()"
        shell: bash
        env:
          CI_PR_BODY: ${{ env.CI_PR_BODY }}

      - name: Create PR to the ansible-documentation
        working-directory: ansible-documentation
        run: |
          gh pr create -B devel -H 'publish-${{ inputs.ansible-version }}' --title '${{ env.CI_COMMIT_MESSAGE }}'  --body-file pr_body.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

