---
name: Create porting guide PR

"on":
  workflow_call:
    inputs:
      repository:
        type: string
        description: The repository to check out.
        required: true
      path:
        type: string
        description: The path for the repository.
        required: true
      ansible-version:
        type: string
        description: Ansible release version.
        required: true
      ansible-major-version:
        type: string
        description: Ansible major version.
        required: true

env:
  GIT_BRANCH: porting-guide-${{ inputs.ansible-version }}
  ANSIBLE_VERSION: ${{ inputs.ansible-version }}
  PORTING_GUIDE_RST: porting_guide_${{ inputs.ansible-major-version }}.rst
  CI_COMMIT_MESSAGE: |-
    Add the Ansible community ${{ inputs.ansible-version }} porting guide
  PR_BODY_MESSAGE: |-
    ##### SUMMARY

    Add the Ansible ${{ inputs.ansible-major-version }} porting guide.

    ##### ISSUE TYPE

    - Docs Pull Request

    ##### COMPONENT NAME

    `porting_guide_${{ inputs.ansible-major-version }}.rst`

jobs:
  create-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        path: ${{ inputs.path }}

    - name: Download the artifact with the RST file
      uses: actions/download-artifact@v4
      with:
        name: ansible-porting-guide
        path: ${{ inputs.path }}

    - name: Copy the RST file to the docs repo
      run: cp -v "${PORTING_GUIDE_RST}" docs/docsite/rst/porting_guides/

    - name: Set up git
      run: |
        git switch --create "${GIT_BRANCH}"
        ACTOR_NAME="$(curl -s https://api.github.com/users/"${GITHUB_ACTOR}" | jq --raw-output '.name // .login')"
        git config --global user.name "${ACTOR_NAME}"
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Add the porting guide
      run: git add docs/docsite/rst/porting_guides/"${PORTING_GUIDE_RST}"

    - name: Commit the porting guide
      run: >-
        git diff-index --quiet HEAD ||
        git commit -m "${CI_COMMIT_MESSAGE}"

    - name: Push to the repo
      run: git push origin "${GIT_BRANCH}"

    - name: Create the porting guide PR
      run: >-
        gh pr create
        --base test
        --head "release/porting-guide-${ANSIBLE_VERSION}"
        --title "${CI_COMMIT_MESSAGE}"
        --body "${PR_BODY_MESSAGE}"
