---
name: nox

"on":
  workflow_call:

jobs:
  nox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Inputs:
          #   session: name of session
          #   python-versions: comma-separated list of Python versions to install
          #   extra-args (optional): extra arguments to pass to nox session.
          - session: static
            python-versions: "3.13"
          - session: formatters_check
            python-versions: "3.13"
          - session: typing
            python-versions: "3.13"
          - session: spelling
            python-versions: "3.13"
          - session: "checkers(rstcheck)"
            python-versions: "3.13"
          - session: "checkers(rst-yamllint)"
            python-versions: "3.13"
          - session: "checkers(docs-build)"
            python-versions: "3.13"
          - session: "actionlint"
            python-versions: "3.13"
          - session: "pip-compile"
            extra-args: "--check"
            python-versions: "3.13"
          - session: "zizmor"
            python-versions: "3.13"
    name: "Run nox ${{ matrix.session }} session"
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup nox
        uses: wntrblm/nox@2026.04.10
        with:
          python-versions: "${{ matrix.python-versions }}"
      - name: Graft ansible-core with Python ${{ matrix.python-versions }}
        run: |
          nox -e clone-core
        with:
          python-versions: "${{ matrix.python-versions }}"
      - name: "Run nox -e ${{ matrix.session }}"
        # Using GHA expression interpolation is fine here,
        # as we control all the inputs.
        # zizmor: ignore[template-injection]
        run: |
          nox -e "${{ matrix.session }}" -- ${{ matrix.extra-args }}
