---
name: nox

"on":
  workflow_call:

jobs:
  nox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Inputs:
          #   session: name of session
          #   python-versions: comma-separated list of Python versions to install
          #   extra-args (optional): extra arguments to pass to nox session.
          - session: static
            python-versions: "3.12"
          - session: formatters_check
            python-versions: "3.12"
          - session: typing
            python-versions: "3.12"
          - session: spelling
            python-versions: "3.12"
          - session: "checkers(rstcheck)"
            python-versions: "3.12"
          - session: "checkers(rst-yamllint)"
            python-versions: "3.12"
          - session: "checkers(docs-build)"
            python-versions: "3.12"
          - session: "actionlint"
            python-versions: "3.12"
          - session: "pip-compile"
            extra-args: "--check"
            python-versions: "3.12"

    name: "Run nox ${{ matrix.session }} session"
    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Setup nox
        uses: wntrblm/nox@2025.05.01
        with:
          python-versions: "${{ inputs.python-versions }}"

      - name: Graft ansible-core
        uses: x1101/github-action-run-nox@ca8b16f76c53a04b14952620e7a4ac5c7dc29812
        with:
          sessions: clone-core
          force-pythons: "${{ inputs.python-versions }}"

      - name: "Run nox session"
        uses: x1101/github-action-run-nox@ca8b16f76c53a04b14952620e7a4ac5c7dc29812
        with:
          sessions: "${{ matrix.sessions }}"
          extra-args: ${{ inputs.extra-args || '' }}
          force-pythons: "${{ inputs.python-versions }}"

