---
name: Sync tags with ansible-core releases

"on":
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: false
        description: "Select to run the tag script in dry-run mode"
  schedule:
    - cron: "0 * * * *"  # Hourly

permissions:
  contents: read  # read-only because we use bot token to push

jobs:
  tag:
    if: github.repository_id == 651282842  # ansible/ansible-documentation
    runs-on: "ubuntu-latest"
    environment: github-bot
    permissions:
      contents: write
    steps:
      - name: Generate temp GITHUB_TOKEN
        id: create_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_KEY }}
          permission-contents: write
      - name: Check out us
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ansible-documentation
          fetch-depth: 0
          token: "${{ steps.create_token.outputs.token }}"
          persist-credentials: true
      - name: Check out core
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ansible/ansible
          path: ansible
          fetch-depth: 0
          persist-credentials: false
      - name: Setup nox
        uses: wntrblm/nox@a976d7ee04ab7a13634adc1016d4755a1348225f # 2026.08.17
        with:
          python-versions: "3.13"
      - name: Set up git committer
        run: |
          ./hacking/get_bot_user.sh "ansible-documentation-bot" "Ansible Documentation Bot"
        working-directory: ansible-documentation
      - name: Run tag script
        run: nox -s tag -- tag ${{ inputs.dry-run && '--no-push' || '' }}
        working-directory: ansible-documentation
