---
name: Build and deploy docs
"on":
  schedule:
    # Run at 05:22 on Monday, Wednesday
    - cron: '22 5 * * 1,3'

jobs:
  build-package-docs:
    name: 📝 Build
    uses: ./.github/workflows/reusable-build-docs.yaml
    with:
      repository-branch: 'stable-2.18'
      ansible-package-version: 'devel'
    secrets:
      DOCS_BOT_TOKEN: ${{ secrets.DOCS_BOT_TOKEN }}

  deploy-package-docs:
    name: 🚀 Deploy
    needs: build-package-docs
    uses: ./.github/workflows/reusable-deploy-docs.yaml
    with:
      ansible-package-version: 'devel'
      deployment-environment: test
      repository-branch: 'stable-2.18'
    secrets:
      DEPLOY_DOC_BUILD: ${{ secrets.DEPLOY_DOC_BUILD }}
